### ISSUE TITLE
Any redirect causes 'errno 32 broken pipe' and appears to ignore region filter

### ISSUE THREAD

**Issue by elasticfusion** [prowler-cloud/prowler#242]
Mac 10.13.6
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)
Python 2.7.14
$ aws --version
aws-cli/1.15.84 Python/2.7.14 Darwin/17.7.0 botocore/1.10.83
$ python -c "import boto3; print boto3.__version__"
1.7.4

I did a git pull just prior to running to make sure I was on latest/greatest.  Still, probably something dumb on my part.

./prowler -r us-east-1 | ansi2html -la > us-east-1-report.html

```$ ./prowler -r us-east-1 | ansi2html -la > us-east-1-report.html
base64: invalid option -- 'D'
Try 'base64 --help' for more information.

[Errno 32] Broken pipe
^CTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/ansi2html", line 11, in <module>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/aws", line 19, in <module>
    import awscli.clidriver
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 36, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansi2html/converter.py", line 560, in main
    from awscli.help import ProviderHelpCommand
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/help.py", line 27, in <module>
    map(_read, sys.stdin.readlines())
KeyboardInterrupt
    from awscli.clidocs import ProviderDocumentEventHandler
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidocs.py", line 21, in <module>
    from awscli.argprocess import ParamShorthandDocGen
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/argprocess.py", line 21, in <module>
    from awscli import shorthand
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/shorthand.py", line 96, in <module>
    class ShorthandParser(object):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/shorthand.py", line 116, in ShorthandParser
    follow_chars=_FIRST_FOLLOW_CHARS,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/shorthand.py", line 51, in __init__
    self.regex = re.compile(regex_str, re.UNICODE)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 194, in compile
    return _compile(pattern, flags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 249, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py", line 576, in compile
    code = _code(p, flags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py", line 561, in _code
    _compile(code, p.data, flags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py", line 140, in _compile
    _compile(code, av[2], flags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py", line 151, in _compile
    _compile(code, av[1], flags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py", line 192, in _compile
    _compile(code, av, flags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py", line 107, in _compile
    _compile_charset(av, flags, code, fixup, fixes)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py", line 232, in _compile_charset
    flags & SRE_FLAG_UNICODE):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sre_compile.py", line 274, in _optimize_charset
    r = range(av[0], av[1]+1)
KeyboardInterrupt```

I waited about 30 seconds befor interupting with the keyboard, after "base64: invalid option -- 'D"  appeared.

Also:

```$ ./prowler -M mono > prowler-report.txt
base64: invalid option -- 'D'
Try 'base64 --help' for more information.

[Errno 32] Broken pipe
^CTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/aws", line 27, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/aws", line 23, in main
    return awscli.clidriver.main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 59, in main
    rc = driver.main()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 194, in main
    command_table = self._get_command_table()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 103, in _get_command_table
    self._command_table = self._build_command_table()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 123, in _build_command_table
    command_object=self)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/session.py", line 721, in emit
    return self._events.emit(event_name, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/hooks.py", line 360, in _emit
    aliased_event_name, kwargs, stop_on_response
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/customizations/preview.py", line 69, in mark_as_preview
    service_name=original_command.service_model.service_name,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 315, in service_model
    return self._get_service_model()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/awscli/clidriver.py", line 335, in _get_service_model
    self._service_name, api_version=api_version)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/session.py", line 537, in get_service_model
    service_description = self.get_service_data(service_name, api_version)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/session.py", line 560, in get_service_data
    api_version=api_version
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/loaders.py", line 374, in load_service_model
    known_services = self.list_available_services(type_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/loaders.py", line 132, in _wrapper
    data = func(self, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/loaders.py", line 284, in list_available_services
    if self.file_loader.exists(full_load_path):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/botocore/loaders.py", line 154, in exists
    return os.path.isfile(file_path + '.json')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 37, in isfile
    st = os.stat(path)
KeyboardInterrupt```

Again I waited about 30 seconds

./prowler -r us-east-1

Example output:

7.28 [extra728] Check if SQS queues have Server Side Encryption enabled (Not Scored) (Not part of CIS benchmark)
       INFO! ap-south-1: No SQS queues found
       INFO! eu-west-3: No SQS queues found
       INFO! eu-west-2: No SQS queues found
       INFO! eu-west-1: No SQS queues found
       INFO! ap-northeast-2: No SQS queues found
       INFO! ap-northeast-1: No SQS queues found
       INFO! sa-east-1: No SQS queues found
       INFO! ca-central-1: No SQS queues found
       INFO! ap-southeast-1: No SQS queues found
       INFO! ap-southeast-2: No SQS queues found
       INFO! eu-central-1: No SQS queues found
       INFO! us-east-1: No SQS queues found
       INFO! us-east-2: No SQS queues found
       INFO! us-west-1: No SQS queues found
       INFO! us-west-2: No SQS queues found

**Comment by elasticfusion** [comment]
I just noticed the HTML file was created but nothing was written to it.

In the "working version", it still threw that error:

```
0.1 Generating AWS IAM Credential Report...
base64: invalid option -- 'D'
Try 'base64 --help' for more information.

[Errno 32] Broken pipe

 1.0 Identity and Access Management - [group1] **********************  
```


But it still ignored the region filter.  So 1/3 maybe 2/3s user error?

The IAM Credential Report sure is handy though.  :-)

**Comment by toniblyx** [comment]
Hi @elasticfusion sorry to respond late. It looks like there is something wrong with the command `base64 -D` in your mac, if you have regular binaries in your mac that command should work fine. What do you get when you run `echo $OSTYPE` in a Terminal? You should get `darwin17`. Also, could you run manually `base64 --help | grep decode`? you should get `-D, --decode   decodes input` if not, your base64 binary is different than what it should be out of the box in a mac. You can try from a docker container with linux also or a ec2 instance instead.

To see how Prowler deals with different `base64` flags in Linux or Mac, please check this line:
https://github.com/toniblyx/prowler/blob/master/include/os_detector#L59

**Comment by toniblyx** [comment]
I'm going to close this issue due to lack of info.
